src/services/index.js

Can be imported from anywhere with import statement.

Added services for distance, location and lobbycode.

---

src/store/modules/course.js
src/views/Stats.vue

Gerdi update a fetchCourses og fetchCourse a stats undirsidunni.

fetchCourses and fetchCourse update

---

src/components/home/Location.vue
src/components/home/Menu.vue
src/components/home/Profile.vue
src/router/index.js
src/services/index.js
src/store/modules/user.js
src/views/Auth.vue
src/views/Stats.vue

Fixed chrome issues.
Fixed mobile layout.

Fixes to Profile and Location. Spiced up Stats.

---

src/graphql/custom/gamegraphQL.js
src/store/modules/game.js

Lobby code verdur til thegar nyr leikur er buinn til og birtist lika thegar gert er get game

lobby code

---

vue.config.js
workbox-config.js

Added a service worker.
Added workbox config.

Service worker that works. Ready for testing

---

src/components/home/Location.vue

Geo-location call works.
Still needs to be connected to the store and ultimately the back-end.

Location service call works

---

src/components/game/CourseInfo.vue
src/components/game/CourseListItem.vue
src/main.js
src/store/modules/course.js
src/store/modules/game.js
src/views/Game.vue
src/views/Lobby.vue

Refactoring

---

amplify/backend/api/frontendapplicationprod/schema.graphql
src/graphql/custom/gamegraphQL.js
src/graphql/custom/playergraphQL.js
src/graphql/mutations.js
src/graphql/queries.js
src/graphql/schema.json
src/graphql/subscriptions.js
src/store/modules/game.js
src/views/Stats.vue

Fix á graphQL schemað, verð að fá þetta inná master svo allt virki

GraphQL schema error

---

src/main.js
src/store/index.js
src/views/Lobby.vue

Auto routing in lobby finally works.

Subscribe auto routing

---

src/graphql/custom/playergraphQL.js
src/store/modules/game.js

When a player joins or leaves lobby the lobby refreshes for everybody.

auto refresh when player joins or leaves lobby

---

src/graphql/custom/gamegraphQL.js
src/graphql/custom/usergraphQL.js
src/store/modules/game.js
src/store/modules/user.js
src/views/Stats.vue

Added timestamp and changed Stats page.
Now everytime a game is created a timestamp is added.
On the stats page current users gamesPlayedInfo is displayed in a beautiful heavily nested JSON format.

timestamp up in this

---

src/views/JoinGame.vue
src/views/Lobby.vue

Now it does not matter if the lobby code is capital or lower case

Fixed All Caps bug

---

src/services/index.js
src/views/JoinGame.vue
src/views/Scorecard.vue

Along with small tweaks to Join Game and services.

PathName bug fixed

---

src/store/index.js
src/store/modules/game.js
src/views/JoinGame.vue
src/views/Stats.vue

Eg skipti út fetchGames falinu fyrir FetchLobbyGame, þarf að gera nokkrar breytingar í framenda í viðbót til að hægt sé að join-a leik í progress. Fer yfir það með ykkur þegar við hittumst á morgun.
Ekkert er brotið en á samt eftir að klára alveg í gegn.

Join game update

---

src/store/modules/game.js
src/views/Lobby.vue

Refresh takkar ordnir virkir, na i nyjan game object ur gagnagrunni og endurnyja subscriptions

refresh lobby and scorecard buttons active

---

src/graphql/custom/usergraphQL.js
src/store/modules/user.js

Hægt að breyta um usernafn núna en vantar input validation þar. Bara mest 3 stafir og vantar að converta yfir í hástafi ef við viljum það.
Default tee er líka tengt en það á eftir að tengja dark light theme í grunninn.

Profile store

---

src/router/index.js
src/store/modules/game.js
src/views/Scorecard.vue

Now the action requires a Boolean as a payload. It is not a toggle function any more.

Fixed hide bottom nav bugs

---

src/store/modules/game.js
src/store/modules/route.js
src/views/Lobby.vue
src/views/Scorecard.vue

Subscription logic komin, þarf að fá inná master og prófa svo í mobile. Fæ að halda console log-um inni á meðan að verið er að ganga úr skugga um að allt sé í góðu.

Subscription logic

---

src/views/Scorecard.vue

attempt two

---

src/views/Scorecard.vue

Fixed keyboard bug and tweaks

---

src/components/game/Course.vue
src/components/game/CourseListItem.vue
src/components/home/Rules.vue
src/graphql/custom/gamegraphQL.js
src/router/index.js
src/store/modules/auth.js
src/store/modules/course.js
src/store/modules/game.js
src/store/modules/route.js
src/store/modules/user.js
src/views/Home.vue
src/views/JoinGame.vue
src/views/Lobby.vue
src/views/Scorecard.vue
src/views/Stats.vue

Mob programming session
